apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 644421735833.dkr.ecr.ap-northeast-1.amazonaws.com/test-bitvleo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4443
